// <auto-generated />
namespace DgrosStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createIdCardColunmIntoClientTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createIdCardColunmIntoClientTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201808240246156_createIdCardColunmIntoClientTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
